[2023-08-04 16:11:24 -0600] [21658] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/cesar/Visual Code Projects/AdopPet/app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f55c5f2e440>
  on_reload: <function OnReload.on_reload at 0x7f55c5f2e560>
  when_ready: <function WhenReady.when_ready at 0x7f55c5f2e680>
  pre_fork: <function Prefork.pre_fork at 0x7f55c5f2e7a0>
  post_fork: <function Postfork.post_fork at 0x7f55c5f2e8c0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f55c5f2e9e0>
  worker_int: <function WorkerInt.worker_int at 0x7f55c5f2eb00>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f55c5f2ec20>
  pre_exec: <function PreExec.pre_exec at 0x7f55c5f2ed40>
  pre_request: <function PreRequest.pre_request at 0x7f55c5f2ee60>
  post_request: <function PostRequest.post_request at 0x7f55c5f2eef0>
  child_exit: <function ChildExit.child_exit at 0x7f55c5f2f010>
  worker_exit: <function WorkerExit.worker_exit at 0x7f55c5f2f130>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f55c5f2f250>
  on_exit: <function OnExit.on_exit at 0x7f55c5f2f370>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f55c5f2f490>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-08-04 16:11:24 -0600] [21658] [INFO] Starting gunicorn 21.2.0
[2023-08-04 16:11:24 -0600] [21658] [DEBUG] Arbiter booted
[2023-08-04 16:11:24 -0600] [21658] [INFO] Listening at: http://0.0.0.0:8000 (21658)
[2023-08-04 16:11:24 -0600] [21658] [INFO] Using worker: sync
[2023-08-04 16:11:24 -0600] [21660] [INFO] Booting worker with pid: 21660
[2023-08-04 16:11:25 -0600] [21658] [DEBUG] 1 workers
[2023-08-04 16:11:25 -0600] [21660] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/cesar/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cesar/Visual Code Projects/AdopPet/app/app.py", line 15, in <module>
    app.route('/usuarios/validar/<str:email>/<str:contrasenia>', methods = ['GET'])(UsuarioController.validar_usuario)
  File "/home/cesar/.local/lib/python3.10/site-packages/flask/scaffold.py", line 436, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/cesar/.local/lib/python3.10/site-packages/flask/scaffold.py", line 51, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/cesar/.local/lib/python3.10/site-packages/flask/app.py", line 1055, in add_url_rule
    self.url_map.add(rule)
  File "/home/cesar/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 198, in add
    rule.bind(self)
  File "/home/cesar/.local/lib/python3.10/site-packages/werkzeug/routing/rules.py", line 562, in bind
    self.compile()
  File "/home/cesar/.local/lib/python3.10/site-packages/werkzeug/routing/rules.py", line 707, in compile
    self._parts.extend(self._parse_rule(rule))
  File "/home/cesar/.local/lib/python3.10/site-packages/werkzeug/routing/rules.py", line 613, in _parse_rule
    convobj = self.get_converter(
  File "/home/cesar/.local/lib/python3.10/site-packages/werkzeug/routing/rules.py", line 576, in get_converter
    raise LookupError(f"the converter {converter_name!r} does not exist")
LookupError: the converter 'str' does not exist
[2023-08-04 16:11:25 -0600] [21660] [INFO] Worker exiting (pid: 21660)
[2023-08-04 16:11:25 -0600] [21658] [ERROR] Worker (pid:21660) exited with code 3
[2023-08-04 16:11:25 -0600] [21658] [ERROR] Shutting down: Master
[2023-08-04 16:11:25 -0600] [21658] [ERROR] Reason: Worker failed to boot.
